pageplanner.settings:
  type: config_object
  label: 'Pageplanner Settings'
  mapping:
    base_url:
      type: string
      label: 'Pageplanner API Base Url'
    access_token_url:
      type: string
      label: 'Access Token URL'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'

node.type.*.third_party.pageplanner:
  type: config_entity
  label: 'Pageplanner'
  mapping:
    field_map:
      type: sequence
      label: 'Field map'
      sequence:
        type: string
